version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.12
    working_directory: /go/src/github.com/hashicorp/vault-plugin-secrets-ad
    steps:
    - checkout
    - run:
        name: "Setup Environment"
        command: |
          echo 'export GO111MODULE=on' >> $BASH_ENV
    - run:
        name: "Run All Tests with Race Detection"
        command: make testrace
    - run:
        name: "Install Gox"
        command: go get github.com/mitchellh/gox
    - run:
        name: "Run Build"
        command: make dev
