name: Run Tests
on:
  push:
jobs:
  run-tests:
    # using `main` as the ref will keep your workflow up-to-date
    uses: hashicorp/vault-workflows-common/.github/workflows/tests.yaml@main

  run-tests-race:
    name: "Run Tests Race"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: .go-version
          cache: true
      - name: Run Tests (Race)
        run: make testrace
