name: Run Tests
on:
  push:
jobs:
  run-tests:
    # using `main` as the ref will keep your workflow up-to-date
    uses: hashicorp/vault-workflows-common/.github/workflows/tests.yaml@main

  run-tests-race:
    name: "Run Tests Race"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: .go-version
          cache: true
      - name: Run Tests (Race)
        run: make testrace
